#pragma checksum "C:\Code\whatshappening\whatshappening\Pages\Bindings.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "db02318b7cf2771a2ad087b97b7245a4b558965de2ade1a983424f9ed5e589fc"
// <auto-generated/>
#pragma warning disable 1591
namespace WhatsHappening.Pages
{
#line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
#nullable restore
#line (1, 2) - (1, 23) "C:\Code\whatshappening\whatshappening\_Imports.razor"
    using System.Net.Http

#nullable disable
        ;
#nullable restore
#line (2, 2) - (2, 28) "C:\Code\whatshappening\whatshappening\_Imports.razor"
    using System.Net.Http.Json

#nullable disable
        ;
#nullable restore
#line (3, 2) - (3, 45) "C:\Code\whatshappening\whatshappening\_Imports.razor"
    using Microsoft.AspNetCore.Components.Forms

#nullable disable
        ;
#nullable restore
#line (4, 2) - (4, 47) "C:\Code\whatshappening\whatshappening\_Imports.razor"
    using Microsoft.AspNetCore.Components.Routing

#nullable disable
        ;
#nullable restore
#line (5, 2) - (5, 43) "C:\Code\whatshappening\whatshappening\_Imports.razor"
    using Microsoft.AspNetCore.Components.Web

#nullable disable
        ;
#nullable restore
#line (6, 2) - (6, 58) "C:\Code\whatshappening\whatshappening\_Imports.razor"
    using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
        ;
#nullable restore
#line (7, 2) - (7, 56) "C:\Code\whatshappening\whatshappening\_Imports.razor"
    using Microsoft.AspNetCore.Components.WebAssembly.Http

#nullable disable
        ;
#nullable restore
#line (8, 2) - (8, 48) "C:\Code\whatshappening\whatshappening\_Imports.razor"
    using Microsoft.FluentUI.AspNetCore.Components

#nullable disable
        ;
#nullable restore
#line (9, 2) - (9, 62) "C:\Code\whatshappening\whatshappening\_Imports.razor"
    using Icons = Microsoft.FluentUI.AspNetCore.Components.Icons

#nullable disable
        ;
#nullable restore
#line (11, 2) - (11, 27) "C:\Code\whatshappening\whatshappening\_Imports.razor"
    using Microsoft.JSInterop

#nullable disable
        ;
#nullable restore
#line (12, 2) - (12, 22) "C:\Code\whatshappening\whatshappening\_Imports.razor"
    using WhatsHappening

#nullable disable
        ;
#nullable restore
#line (13, 2) - (13, 29) "C:\Code\whatshappening\whatshappening\_Imports.razor"
    using WhatsHappening.Layout

#nullable disable
        ;
#line default
#line hidden
#nullable restore
    public partial class Bindings_Code : global::Microsoft.AspNetCore.Components.ComponentBase
#nullable disable
    {
#pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenComponent<global::WhatsHappening.Pages.FindImportantStrings>(0);
            __builder.AddComponentParameter(1, nameof(global::WhatsHappening.Pages.FindImportantStrings.
#nullable restore
#line (6,23)-(6,33) "C:\Code\whatshappening\whatshappening\Pages\Bindings.razor"
AllStrings

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.String>>(
#nullable restore
#line (6,35)-(6,42) "C:\Code\whatshappening\whatshappening\Pages\Bindings.razor"
strings

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(2, nameof(global::WhatsHappening.Pages.FindImportantStrings.
#nullable restore
#line (6,50)-(6,66) "C:\Code\whatshappening\whatshappening\Pages\Bindings.razor"
ImportantStrings

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Collections.Generic.IEnumerable<global::System.String>>(
#nullable restore
#line (6,68)-(6,84) "C:\Code\whatshappening\whatshappening\Pages\Bindings.razor"
importantStrings

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(3, nameof(global::WhatsHappening.Pages.FindImportantStrings.ImportantStringsChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::System.Collections.Generic.IEnumerable<System.String>>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::System.Collections.Generic.IEnumerable<System.String>>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => importantStrings = __value, importantStrings))));
            __builder.CloseComponent();
        }
#pragma warning restore 1998
#nullable restore
#line (2, 2) - (5, 1) "C:\Code\whatshappening\whatshappening\Pages\Bindings.razor"

        List<string> strings = ["a", "bunch", "of", "strings"];
        HashSet<string> importantStrings = [];

#line default
#line hidden
#nullable disable

    }
}
#pragma warning restore 1591
